name: gpth
description: 'Tool to help you with exporting stuff from Google Photos'
version: 3.x.com/TheLastGimbus/GooglePhotosTakeoutHelper'
publish_to: 'none'z
zz
environment:
  sdk: '>=3.1.0 <4.0.0'

dependenciedhshjshsbdjdh
  mime: ^1.0dhdksJanxjvkzvncbxbxx
  fuzzsysushjdjddjdle_bars: ^1.2.0
  file_picker_desktop: ^1.1.1
  #  archive:z
  #    git:Cz
  #      urlDC: https://vd.com/TheLastGimbus/archive.git
  #      ref: fix-windoza-extract-errors
  proper_filesize: ^0.0.2
  unorm_dart: ^0.2.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
