# Main Dart tests and checks
name: Dart tests

on:
  push:
    branches: [ master ]
  pull_request:
rytrttr
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos
